version: '2.2'

services:
  insite-db:
    image: postgres:15-alpine
    container_name: insite-api-db
    restart: always
    environment:
      POSTGRES_USER: apihub
      POSTGRES_PASSWORD: apihub_password
      POSTGRES_DB: apihub
    ports:
      - "7000:5432"
    volumes:
      - insite_postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - insite-network

  insite-app:
    build: .
    container_name: insite-api-app
    restart: always
    ports:
      - "3005:3005"
    environment:
      DATABASE_URL: postgresql://apihub:apihub_password@insite-db:5432/apihub
    depends_on:
      - insite-db
    networks:
      - insite-network

networks:
  insite-network:
    driver: bridge

volumes:
  insite_postgres_data:
